gastighost/help-local

- pages/api/movies.js
- util/mongodb.js
Connected the sample database to the api folder javascript file.
> read sample data from mongodb

- components/humanitarian-aid/humanitarian-aid-item.js
- components/humanitarian-aid/humanitarian-aid-item.module.css
- components/humanitarian-aid/humanitarian-aid-list.js
- components/humanitarian-aid/humanitarian-aid-list.module.css
- pages/humanitarian-aid/index.js
- styles/Home.module.css
Added components for humanitarian aid. Also added css modules for each component.
> implement card index component functionality for humanitarian aid

- package-lock.json
- yarn.lock
> add package json changes

- components/humanitarian-aid/humanitarian-aid-list.js
- components/jobs/jobs-item.js
- components/jobs/jobs-list.js
- components/ui/card.js
- pages/jobs/index.js
- Pulled the `<li>` elements out of the card component, so it can be used more generally. Inserted the `<li>` element in `components/humanitarian-aid/humanitarian-aid-list.js` again, so the `<ul>` list works again there.
- Created some dummy jobs to work with for now in `jobs/index.js`
- Created jobsList and jobsItem components to render the jobs on `jobs/index.js`
> Create job page with samples and card

- components/humanitarian-aid/humanitarian-aid-list.js
- next.config.js
Added security headers into next.js application to improve website security.
> add security headers and key for each list item in aid components

- components/education/EducationItem.js
- components/education/EducationItem.module.css
- components/education/EducationList.js
- pages/education/index.js
Added EducationList.js, EducationItem.js (with their CSS modules). 
Implemented EducationIndex function in Index.js (education directory)
> Education listings completed

- components/ui/button.js
- components/ui/button.module.css
- components/ui/filter-bar.js
- components/ui/filter-bar.module.css
- pages/education/index.js
- pages/humanitarian-aid/index.js
- pages/jobs/index.js
- pages/social-media/index.js
Added filter navbar in order to  change directories.
> add filter navbar to top of each category index page

- components/humanitarian-aid/humanitarian-aid-item.js
- components/humanitarian-aid/humanitarian-aid-list.js
- pages/humanitarian-aid/[aidId].js
- pages/humanitarian-aid/index.js
Created a show page for each index item on the humanitarian aid category.
> Category h

- components/auth/auth-form.js
- components/auth/auth-form.module.css
- components/layout/MainNavigation.js
- components/layout/MainNavigation.module.css
- lib/auth.js
- package-lock.json
- package.json
- pages/api/auth/[...nextauth].js
- pages/api/auth/signup.js
- pages/auth.js
- yarn.lock
Authentication is not completed yet, still a bit of stuff to do but with this build you can:
1. Sign up as a new user. 
2. Save user credentials with password hash to MongoDB.
3. Sign in (system checks for user and returns response in browser console if no user exists or returns different response if password is incorrect or returns no error if sign in is successful). 
Also added form for sign up and sign in. 
What you cannot do yet with this build 
1. Authorize pages based on if you're signed in or not (to do in next branch), 
2. Log out of a client session ( " ),
3. Change password ( " )
> Authentication

- yarn.lock
> npm installation update for yarn lock file

- components/humanitarian-aid/humanitarian-aid-form.js
- components/humanitarian-aid/humanitarian-aid-item.js
- components/humanitarian-aid/humanitarian-aid-list.js
- package-lock.json
- package.json
- pages/api/humanitarian-aid/index.js
- pages/humanitarian-aid/[aidId].js
- pages/humanitarian-aid/index.js
- pages/humanitarian-aid/new-aid.js
- pages/humanitarian-aid/newAid.js
- util/mongodb.js
- yarn.lock
Created a form that creates new items for humanitarian aid. Also reconfigured the read logic and get request to the util/mongodb file. Made use of the api folder in pages to implement create requests.
> Api routing

- pages/api/humanitarian-aid/index.js
Fixed the client close function on the api router.
> fix client.close functionality for api request

- components/humanitarian-aid/edit-delete.js
- components/humanitarian-aid/humanitarian-aid-form.js
- pages/api/humanitarian-aid/[aidId].js
- pages/humanitarian-aid/[aidId].js
- util/mongodb.js
Created the delete functionality on the util/mongodb.js file and added an api route which deletes instances of a humanitarian item.
> Delete update api

- components/humanitarian-aid/aid-edit-form.js
- components/humanitarian-aid/edit-delete.js
- pages/api/humanitarian-aid/[aidId].js
- pages/humanitarian-aid/[aidId].js
- util/mongodb.js
Added working api update route that takes in user input to edit existing humanitarian items.
> added working update api route

- package-lock.json
- yarn.lock
Just another npm module fix. Nothing big.
> another npm module fix

- yarn.lock
Just a quick fix on yarn lock dependencies.
> yarn lock fixes

- components/ui/ItemsList.js
Just a simple fix fixing the spelling of the import item in item list js file.
> fix import item in itemslist spelling

- pages/api/auth/[...nextauth].js
- pages/api/humanitarian-aid/index.js
- pages/humanitarian-aid/[aidId].js
I added methods in the api route file to grab the current logged in user's ID so that it could be added as a field in each created object of a humanitarian item. Also added a function in the nextauth api file to allow the grabbing of a current logged in user's ID from any other file in the application.
> add logged in user's id to created humanitarian aid item

- next.config.js
Just some configuration to the next.config.js file in order to deploy to vercel.
> Deployment configuration

- components/education/EducationList.js
- next.config.js
Just  a fix which enables webpack to be consistent with vercel.
> added webpack configuration fix to next.config

- components/jobs/jobs-list.js
- pages/api/jobs/index.js
- pages/jobs/index.js
-  Made changes to `pages/jobs/index.js` so that it is getting all jobs by reading from database collection jobs. 
- Deleted dummy data for jobs in `pages/jobs/index.js` as it is not needed anymore.
- Created `pages/api/jobs/index.js` as preparation for the next [feature](https://github.com/gastighost/new-in-germany/projects/1#card-81042437) enabling creating a new job and inserting a new document into the database collection.
> Connecting jobs to database

- components/jobs/jobs-item.js
- components/jobs/jobs-list.js
- pages/jobs/[jobId].js
- pages/jobs/new-job.js
Just a quick fix in naming convention for the jobs react components.
> renamed jobs list and jobs item to match correct capitalization

- components/jobs/jobs-item.js
- pages/jobs/[jobId].js
When viewing the jobs index page, the user can now click and open a view page of each single job item.
> user can now see show page of one single job

- components/jobs/jobs-form.js
- pages/api/jobs/index.js
- pages/jobs/new-job.js
User can now create a new job using the create job link on job index page which leads to a form.
Features still missing:
- api doesn't check if user is logged in
- styling and popup missing
> Create new job

- components/education/EducationItem.js
- pages/api/education/index.js
- store/BookmarksContext.js
Bookmarks connected to the DB with the help of useEffect hook.
> Bookmarks 

- components/humanitarian-aid/aid-edit-form.js
- components/humanitarian-aid/aid-item-detail.js
- components/humanitarian-aid/edit-delete.js
- components/humanitarian-aid/humanitarian-aid-form.js
- components/humanitarian-aid/humanitarian-aid-form.module.css
- components/ui/Item.js
- components/ui/ItemsList.js
- components/ui/request-button.js
- pages/api/humanitarian-aid/[aidId].js
- pages/api/humanitarian-aid/index.js
- pages/humanitarian-aid/[aidId].js
- pages/humanitarian-aid/index.js
- pages/humanitarian-aid/new-aid.js
The user can now only create an instance of a humanitarian aid when logged in.
Only the creator of a humanitarian aid instance can mark the item as requested, along with being able to edit or delete the instance.
> Humanitarian form styles

- components/education/EducationItem.js
- components/ui/Item.js
- pages/bookmarks.js
- store/BookmarksContext.js
Now bookmarks are being saved to the local storage (browser cookies) rather than our DB.
This way, we can ensure optimal speed of our app as the bookmarked items no longer have to communicate with the DB. Instead, the array of Bookmarks is being converted to JSON and then save in the local storage.
> Reconfigured bookmarks with local storage instead of MongoDB

- components/jobs/JobEditForm.js
- components/jobs/jobs-form.js
- pages/api/jobs/[jobId].js
- pages/api/jobs/index.js
- pages/jobs/[jobId].js
- pages/jobs/index.js
- jobs can now only be edited or deleted by the user who created it
> Jobs auth user

- package-lock.json
- pages/humanitarian-aid/index.js
- yarn.lock
Added an scss import naming fix when importing Home.module.scss for the index page of humanitarian aid.
> add a scss importing fix in humanitarian index page

- styles/global_styles.scss
- yarn.lock
I fixed the force merge issue by removing the merge comments from the scss files in styles folder.
> fixed the globals css files from force merge

- components/social-media/greeting.js
- components/social-media/greeting.module.scss
- package-lock.json
- package.json
- pages/social-media/index.js
- yarn.lock
Please review my setup for social media site.
> Setup has been done

- components/social-media/cardcontainer.js
- components/social-media/cardcontainer.module.scss
- components/social-media/topbox.js
- components/social-media/topbox.module.scss
Please review and merge, styling is not quite there yet.
> setting up card elements

- components/jobs/JobList.js
Added a key to each render of the mapped job item components.
> added key to each job item component

- components/social-media/cardcontainer.js
- components/social-media/cardcontainer.module.scss
Please merge – added basic design for social media cards.
> finished basic paddings & hierarchies

- components/social-media/cardcontainer.js
- components/social-media/cardcontainer.module.scss
- styles/globals.scss
Social-media-card-styling is 80% done. Also added some general font-styles.
> almost finished with card

- components/social-media/cardcontainer.js
- components/social-media/cardcontainer.module.scss
Didn't manage to set up the modal, but card-design is finished now. Please merge!
> Not done with modal, card is styled though.
